apiVersion: apps/v1
kind: Deployment
metadata:
  name: storybook
spec:
  selector:
    matchLabels:
      app: storybook
  replicas: 1
  template:
    metadata:
      labels:
        app: storybook
    spec:
      containers:
        - name: storybook
          image: solid-ui-storybook
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6006
